import Head from 'next/head';
import Card from '../components/Card';
import styled from '@emotion/styled';
import { Fetcher } from './api/fetch';
import ConnectionFail from '../components/ConnectionFail';

export default function Home({ movies }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="container">
        <CardsStyled>
          {movies ? (
            movies.data.map((item) => {
              return (
                <Card
                  key={item.id}
                  title={item.attributes.title}
                  img={item.attributes.poster.data.attributes.url}
                  slug={item.attributes.slug}
                  genre={
                    item.attributes.genre.data
                      ? item.attributes.genre.data.attributes.slug
                      : 'uncategorized'
                  }
                  width={item.attributes.poster.data.attributes.width}
                  height={item.attributes.poster.data.attributes.height}
                />
              );
            })
          ) : (
            <ConnectionFail />
          )}
        </CardsStyled>
      </div>
    </>
  );
}

const CardsStyled = styled.div`
  display: grid;
  grid-template-columns: 1fr 1fr 1fr;
  grid-gap: 30px;
`;

export async function getServerSideProps() {
  const data = await Fetcher('movies?populate=poster,genre');

  return {
    props: {
      movies: data,
    },
  };
}
